# Longitudinal Mediation Analysis 

As in all path diagrams, you write an equation for each “endogenous” variable (ones which have arrows drawn to them), and the predictors in each equation are the variables which have arrows pointing to the endogenous variable. 
Thus, in the first diagram, DV has one equation, in which the predictors are Mediator and IV, and Mediator has one equation, in which IV is the only predictor.
In longitudinal mediation, you are looking at mediation over time. Thus, in randomized control trials (RCTs), the IV is often Time and the M and DV are both measured repeatedly over time. 
The IV could also be treatment condition in RCTs. We will look at this both ways. 
Usually, the first step in mediation is to establish that the DV changes over time (c path), or more generally, if the IV effects the DV. If it doesn’t change over time, it is often not so interesting to see if something mediates changes. 
But, this is not always true. Sometimes you may be interested in the mediation of effects even if there is no net change over time. For example, the direct effect of IV on DV (c’) may be positive, while the indirect effect (a*b) through the mediator is negative. The net effect (c) may be near zero.

 