--- 
title: "MLM Study Guide for Caroline, by Caroline"
author: "For doing better, for remediation. Integrating David's class materials and Hoffman's (2015) Longitudinal Analysis textbook to learn MLM with both R and SPSS."
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
---

# First, why multilevel modeling?

Multilevel modeling improves upon disadvantages posed by **repeated measures ANOVA** (RANOVA), simple data imputation such as **last observation carried forward** (LOCF), and **complex imputation** (e.g., multiple imputation). 

## Disadvantages of RANOVA 

- Restrictive assumptions (sphericity: the correlation between any 2 asmts are the same) that are not generally met (the r between asmt 1 and asmt 2 is usually much bigger than between asmt 1 and asmt 5).
- Homogeneity of variance across time
- RANOVA requires complete data-otherwise a subject is dropped. Problems with this include:
    - Completers may not be representative of the population
		- Lose power
		- Assumes data missing completely at random (MCAR), which is almost never true.

## Disadvantages of LOCF

- Solves the power and generalizability issues by including all subjects
- But tends to underestimate group differences if one group is changing more than the other.  
- It also may have unpredictable effects on group differences if reasons for dropout are not random (e.g., some may drop out because they are doing poorly, while others may drop out because they are doing well, and these reasons may vary between groups).

## Disadvantages of complex imputation (e.g., multiple imputation)

- Must create multiple data sets 
- "Pooling" of statistical tests results in low power
- Still have problems with RANOVA in terms of sphericity/homogeneity of variance 

## Advantages of MLM 

- MLM uses all obtained data from all subjects even if they drop out, improving generalizability and accuracy
- Less restrictive assumptions than RANOVA (sphericity, homogeneity of variance not assumed).
- More accurate estimates than LOCF (which tends to underestimate effects) and RANOVA (which is biased by dropouts)
- More powerful than multiple imputation
- Because estimates from MLM use all the data from each subject, these estimates have lower variance and greater reliability than “point” estimates (like in ANCOVA).
- Assumes data missing at random (MAR), not the more restrictive MCAR.


 